### ISSUE TITLE
Add Product

### ISSUE THREAD

**Issue by KoushikMallik-developer** [Techomato/ecom-api-v1#3]
As an e-commerce seller I want to enlist, remove and update my products in the store.

Acceptance Criteria:
- new endpoint to add product.
method: POST
path: api/v1/add-product
request_body: `{
product_name: str,
brand: str,
count_in_stock: int,
category: Optional[str],
subcategory: Optional[str],
image: str
}`
- New endpoint to remove product.
method: POST
path: api/v1/remove-product
request_body: `{
product_id: str
}`
-  new endpoint to update product.
method: POST
path: api/v1/update-product
request_body: `{
product_id: Optional[str],
product_name: Optional[str],
brand: Optional[str],
count_in_stock: Optional[str],
category: Optional[str],
subcategory: Optional[str],
image: Optional[str],
}`

**Comment by animeshrick** [comment]
Done.
